import './News.css';

const severityLevels = [
  { name: 'Normal', color: '#4caf50', icon: '🟢', description: 'A stable emotional and mental state with baseline stress levels that do not interfere with daily functioning, focus, or well-being.' },
  { name: 'Moderate', color: '#ff9800', icon: '🟡', description: 'Noticeable psychological or physical stress symptoms that begin to affect daily functioning, causing occasional disruptions in focus, sleep, or mood.' },
  { name: 'Severe', color: '#f44336', icon: '🔴', description: 'Intense and persistent symptoms that significantly impair daily life, cognitive function, and emotional stability. Professional support is strongly recommended.' },
];

const psychologicalProblems = [
  { name: 'Social Anxiety', icon: '👥', description: 'Intense, persistent fear of being watched and judged by others, often leading to avoidance of social or performance situations.' },
  { name: 'PTSD', icon: '🧠', description: 'A mental health condition triggered by experiencing or witnessing a terrifying event, characterized by flashbacks, nightmares, and severe anxiety.' },
  { name: 'Panic Attack', icon: '⚡', description: 'Sudden episodes of intense fear or discomfort that peak within minutes, often accompanied by physical symptoms like heart palpitations and shortness of breath.' },
  { name: 'GAD', icon: '🌀', description: 'Generalized Anxiety Disorder involves excessive, uncontrollable worry about everyday issues—such as health, finances, or academic performance.' },
  { name: 'Agoraphobia', icon: '🏠', description: 'Fear of being in places or situations where escape might be difficult, or where help may not be available in the event of panic symptoms.' },
];

const educationalProblems = [
  { name: 'Perfectionism', icon: '🎯', description: 'Setting unrealistically high expectations for oneself, leading to harsh self-criticism, fear of making mistakes, and immense pressure.' },
  { name: 'Impostor Syndrome', icon: '🎭', description: 'A psychological pattern where individuals doubt their skills or accomplishments and have a persistent internalized fear of being exposed as a fraud.' },
  { name: 'Test Anxiety', icon: '📝', description: 'A combination of physical symptoms and emotional reactions that occur before or during exams, significantly hindering academic performance.' },
  { name: 'Academic Burnout', icon: '🔥', description: 'A state of chronic exhaustion, cynicism, and reduced professional efficacy caused by prolonged academic stress and excessive workload.' },
  { name: 'Low Self Esteem', icon: '📉', description: 'A subjective evaluation of ones own worth characterized by a lack of confidence and feeling consistently inadequate compared to peers.' },
  { name: 'Lack Of Academic Support', icon: '🚫', description: 'The absence of necessary guidance, resources, or emotional backing from educators, peers, or family to succeed academically.' },
  { name: 'Fear Of Failure', icon: '🛑', description: 'An irrational and persistent fear of failing that paralyzes decision-making and prevents individuals from attempting new academic challenges.' },
  { name: 'Poor Time Management', icon: '⏳', description: 'Difficulty in planning and exercising conscious control of time spent on specific activities, often resulting in procrastination and chronic stress.' },
  { name: 'Pressure Of Surroundings', icon: '🌪️', description: 'The intense stress generated by expectations from family, peers, or society to achieve specific academic or career milestones.' },
  { name: 'Performance Anxiety', icon: '🎤', description: 'Fear about ones ability to perform a specific task, such as a presentation or recital, leading to worry that directly degrades performance quality.' },
  { name: 'Specific Phobia', icon: '🕷️', description: 'An intense, irrational fear of a specific trigger (such as public speaking or a particular academic subject) that poses little or no actual danger.' },
];

const keyTerms = [
  { name: 'Acoustic Vitals (Biomarkers)', icon: '🗣️', description: 'Measurable vocal characteristics, such as Pitch, Jitter, and Shimmer, that act as physiological lie detectors revealing physical stress.' },
  { name: 'Likert Scale Intake', icon: '📋', description: 'A psychometric assessment used during client setup to quantify the frequency of specific anxiety or trauma symptoms (0-3 scale).' },
  { name: 'Severity Router', icon: '🔀', description: 'An intelligent filtration system that determines which specific AI models to load based on clinical urgency and client history.' },
  { name: 'Baseline Severity', icon: '📈', description: 'The initial psychological risk level calculated purely from textual symptom tracking before acoustic parameters are applied.' },
];

function News() {
  return (
    <div className="news">
      <div className="news__hero">
        <h1 className="news__hero-title">Understanding Clinical <span className="news__accent">Assessments</span></h1>
        <p className="news__hero-subtitle">Our platform tracks specific severity levels, psychological conditions, and educational stressors to build a comprehensive acoustic baseline.</p>
      </div>

      {/* Severity Levels */}
      <section className="news__section">
        <h2 className="news__section-title">
          <span className="news__section-icon">📊</span>
          Severity Classification
        </h2>
        <p className="news__section-desc">Our system classifies psychological stress severity into three distinct levels based on text and acoustic biomarkers.</p>
        <div className="news__grid">
          {severityLevels.map(item => (
            <div className="news__card" key={item.name} style={{ borderTopColor: item.color }}>
              <div className="news__card-header">
                <span className="news__card-icon">{item.icon}</span>
                <h3 className="news__card-name" style={{ color: item.color }}>{item.name}</h3>
              </div>
              <p className="news__card-desc">{item.description}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Psychological Problems */}
      <section className="news__section">
        <h2 className="news__section-title">
          <span className="news__section-icon">🧠</span>
          Psychological Problems
        </h2>
        <p className="news__section-desc">We detect patterns indicative of the following core clinical anxiety disorders and traumatic stress indicators.</p>
        <div className="news__grid news__grid--list">
          {psychologicalProblems.map(item => (
            <div className="news__card news__card--horizontal" key={item.name}>
              <span className="news__card-icon news__card-icon--large">{item.icon}</span>
              <div className="news__card-body">
                <h3 className="news__card-name">{item.name}</h3>
                <p className="news__card-desc">{item.description}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Educational Problems */}
      <section className="news__section">
        <h2 className="news__section-title">
          <span className="news__section-icon">📚</span>
          Educational Problems
        </h2>
        <p className="news__section-desc">Academic environments introduce unique stressors. Our neutral baseline tracking looks for signs of these educational challenges.</p>
        <div className="news__grid news__grid--list">
          {educationalProblems.map(item => (
            <div className="news__card news__card--horizontal" key={item.name}>
              <span className="news__card-icon news__card-icon--large">{item.icon}</span>
              <div className="news__card-body">
                <h3 className="news__card-name">{item.name}</h3>
                <p className="news__card-desc">{item.description}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Key Terms */}
      <section className="news__section">
        <h2 className="news__section-title">
          <span className="news__section-icon">📖</span>
          System Key Terms
        </h2>
        <p className="news__section-desc">Familiarize yourself with the core clinical terminologies underlying our voice analysis engine.</p>
        <div className="news__grid news__grid--list">
          {keyTerms.map(item => (
            <div className="news__card news__card--horizontal" key={item.name}>
              <span className="news__card-icon news__card-icon--large">{item.icon}</span>
              <div className="news__card-body">
                <h3 className="news__card-name">{item.name}</h3>
                <p className="news__card-desc">{item.description}</p>
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}

export default News;
